# -*- coding: utf-8 -*-
"""Deliverable 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GE4sypCnalnbQ0-MvnQOOMcoS10OZ9kw
"""

import pandas as pd

# Ask user to input integer 
n= int(input("Enter an integer greater than 0:"))
if n <= 0:
  print ("Invalid Input")

# Create even, odd, and fibonacci numbers 
even_nums = []
odd_nums = []
fib_nums = []
i = 0
while len(even_nums) < n:
    even_nums.append(i)
    i += 2
i = 1
while len(odd_nums) < n:
    odd_nums.append(i)
    i += 2
i, j = 0, 1
while len(fib_nums) < n:
    fib_nums.append(i)
    i, j = j, i+j

# Create data frame and display results 
df = pd.DataFrame({
    'Even': even_nums,
    'Odd': odd_nums,
    'Fibonacci': fib_nums
})
print(df)